export const blogsArray = [
    {
        id: 0,
        title: 'Warm like the sun',
        parapgraphs: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, placeat eveniet ipsa saepe repellendus porro officiis similique suscipit exercitationem quae.", "Fusce venenatis enim sit amet nisl hendrerit dictum. Proin eget suscipit dui. Etiam dignissim est tellus, a euismod nibh dignissim sed. Pellentesque vel ante feugiat, maximus diam a, commodo risus. Aenean mattis ipsum in velit pulvinar, vitae fermentum felis accumsan. Cras placerat ipsum vitae tincidunt mattis. Donec quis neque eget mi porta faucibus. Vivamus purus nisi, ultrices vitae maximus nec, maximus ut lectus. Nulla elementum consectetur mattis. Nunc a turpis in ipsum pulvinar mattis. Vivamus aliquam quam quis nisl euismod, at tempus justo ultrices. Pellentesque ligula dolor, tempor a dolor sed, porta fermentum mauris.", " Nulla porttitor, libero vel auctor convallis, tellus odio feugiat sem, sed suscipit mi arcu at magna. Praesent tincidunt lobortis dui, nec condimentum purus dapibus sit amet. Suspendisse efficitur rhoncus leo. Etiam sagittis neque sed tincidunt pulvinar. Suspendisse enim ligula, finibus et justo quis, viverra dapibus ante. Phasellus ut suscipit urna. Nullam nunc tellus, scelerisque quis mi sed, venenatis dignissim elit. Aliquam ultricies sem eget elit ullamcorper, non pharetra metus imperdiet. Sed vulputate justo eget velit pulvinar rutrum egestas et turpis. Donec dignissim hendrerit libero ut lobortis. Etiam efficitur ante posuere ipsum auctor, quis condimentum ligula sagittis. Integer feugiat elit vel lacinia euismod. ", "Donec congue erat risus, quis iaculis turpis tempus sed. Nulla eget luctus leo. Donec ex turpis, mollis non ligula in, luctus posuere enim. Sed nec lectus felis. Suspendisse cursus lorem vel tristique interdum. Aliquam dictum lacus lorem, id placerat magna tempor vel. Nam ultricies rutrum massa, eu rutrum nulla convallis sed. Donec eget bibendum nunc. Sed rutrum urna vel magna ultrices, cursus commodo mi aliquet. "],
        date: "02.02.2021",
        images: [
            "https://images.unsplash.com/photo-1615529151169-7b1ff50dc7f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80",
            "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2009/10/8/0/DP_balis-orange-brown-livingroom_s4x3.jpg.rend.hgtvcom.966.725.suffix/1400949588840.jpeg",
            "https://i.pinimg.com/originals/3a/75/fe/3a75febee68bcb9d74fd3f1ea80148b6.jpg",
            "https://i.pinimg.com/originals/2c/f7/31/2cf73181b4206d8f95a9d4f9e9ae072a.jpg",
            "https://www.wow1day.com/sites/default/files/national-blog/W1D_blog_WPC_1.png",
            "https://foyr.com/learn/wp-content/uploads/2021/07/traditional-living-rooms-colors.png",
            "https://www.avso.org/wp-content/uploads/files/4/7/1/wall-color-brown-tones-warm-and-natural-3-471.jpg",
            "https://mlqbjdehxf1v.i.optimole.com/WD39P5w.1pPT~47b0b/w:457/h:568/q:auto/https://www.trendlocus.com/wp-content/uploads/2020/11/warm-color-living-room-e1606279988686.png"
        ],
    },
    {
        id: 1,
        title: 'Accents of Blue ',
        parapgraphs: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, placeat eveniet ipsa saepe repellendus porro officiis similique suscipit exercitationem quae.", "Fusce venenatis enim sit amet nisl hendrerit dictum. Proin eget suscipit dui. Etiam dignissim est tellus, a euismod nibh dignissim sed. Pellentesque vel ante feugiat, maximus diam a, commodo risus. Aenean mattis ipsum in velit pulvinar, vitae fermentum felis accumsan. Cras placerat ipsum vitae tincidunt mattis. Donec quis neque eget mi porta faucibus. Vivamus purus nisi, ultrices vitae maximus nec, maximus ut lectus. Nulla elementum consectetur mattis. Nunc a turpis in ipsum pulvinar mattis. Vivamus aliquam quam quis nisl euismod, at tempus justo ultrices. Pellentesque ligula dolor, tempor a dolor sed, porta fermentum mauris.", " Nulla porttitor, libero vel auctor convallis, tellus odio feugiat sem, sed suscipit mi arcu at magna. Praesent tincidunt lobortis dui, nec condimentum purus dapibus sit amet. Suspendisse efficitur rhoncus leo. Etiam sagittis neque sed tincidunt pulvinar. Suspendisse enim ligula, finibus et justo quis, viverra dapibus ante. Phasellus ut suscipit urna. Nullam nunc tellus, scelerisque quis mi sed, venenatis dignissim elit. Aliquam ultricies sem eget elit ullamcorper, non pharetra metus imperdiet. Sed vulputate justo eget velit pulvinar rutrum egestas et turpis. Donec dignissim hendrerit libero ut lobortis. Etiam efficitur ante posuere ipsum auctor, quis condimentum ligula sagittis. Integer feugiat elit vel lacinia euismod. ", "Donec congue erat risus, quis iaculis turpis tempus sed. Nulla eget luctus leo. Donec ex turpis, mollis non ligula in, luctus posuere enim. Sed nec lectus felis. Suspendisse cursus lorem vel tristique interdum. Aliquam dictum lacus lorem, id placerat magna tempor vel. Nam ultricies rutrum massa, eu rutrum nulla convallis sed. Donec eget bibendum nunc. Sed rutrum urna vel magna ultrices, cursus commodo mi aliquet. "],
        date: "01.03.2017",
        images: ["https://images.unsplash.com/photo-1556910638-6cdac31d44dc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80", "https://images.unsplash.com/photo-1556910602-38f53e68e15d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80", "https://images.unsplash.com/photo-1556910591-c01184bb213a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80", "https://images.unsplash.com/photo-1556910633-5099dc3971e8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80", "https://images.unsplash.com/photo-1556910571-72dd87c0abe8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80", "https://images.unsplash.com/photo-1556910109-a14b4226abff?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", "https://images.unsplash.com/photo-1556910103-1c02745aae4d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80", "https://images.unsplash.com/photo-1556910146-6121b9613959?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"],
    },
    {
        id: 2,
        title: 'Summer in your home',
        parapgraphs: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, placeat eveniet ipsa saepe repellendus porro officiis similique suscipit exercitationem quae.", "Fusce venenatis enim sit amet nisl hendrerit dictum. Proin eget suscipit dui. Etiam dignissim est tellus, a euismod nibh dignissim sed. Pellentesque vel ante feugiat, maximus diam a, commodo risus. Aenean mattis ipsum in velit pulvinar, vitae fermentum felis accumsan. Cras placerat ipsum vitae tincidunt mattis. Donec quis neque eget mi porta faucibus. Vivamus purus nisi, ultrices vitae maximus nec, maximus ut lectus. Nulla elementum consectetur mattis. Nunc a turpis in ipsum pulvinar mattis. Vivamus aliquam quam quis nisl euismod, at tempus justo ultrices. Pellentesque ligula dolor, tempor a dolor sed, porta fermentum mauris.", " Nulla porttitor, libero vel auctor convallis, tellus odio feugiat sem, sed suscipit mi arcu at magna. Praesent tincidunt lobortis dui, nec condimentum purus dapibus sit amet. Suspendisse efficitur rhoncus leo. Etiam sagittis neque sed tincidunt pulvinar. Suspendisse enim ligula, finibus et justo quis, viverra dapibus ante. Phasellus ut suscipit urna. Nullam nunc tellus, scelerisque quis mi sed, venenatis dignissim elit. Aliquam ultricies sem eget elit ullamcorper, non pharetra metus imperdiet. Sed vulputate justo eget velit pulvinar rutrum egestas et turpis. Donec dignissim hendrerit libero ut lobortis. Etiam efficitur ante posuere ipsum auctor, quis condimentum ligula sagittis. Integer feugiat elit vel lacinia euismod. ", "Donec congue erat risus, quis iaculis turpis tempus sed. Nulla eget luctus leo. Donec ex turpis, mollis non ligula in, luctus posuere enim. Sed nec lectus felis. Suspendisse cursus lorem vel tristique interdum. Aliquam dictum lacus lorem, id placerat magna tempor vel. Nam ultricies rutrum massa, eu rutrum nulla convallis sed. Donec eget bibendum nunc. Sed rutrum urna vel magna ultrices, cursus commodo mi aliquet. "],
        date: "30.03.2018",
        images: ["https://images.unsplash.com/photo-1522444195799-478538b28823?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", "https://images.pexels.com/photos/3965520/pexels-photo-3965520.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", "https://images.pexels.com/photos/6283843/pexels-photo-6283843.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
            "http://cdn.home-designing.com/wp-content/uploads/2016/01/light-yellow-living-room.png", "https://i.pinimg.com/originals/58/e8/80/58e8808571fb25df69fe7fa8778c9cc2.jpg",
            "https://i.pinimg.com/564x/6e/51/05/6e5105d23aa0c3a51145258c7720a609.jpg",
            "https://www.barkerandstonehouse.co.uk/wp/wp-content/uploads/2020/06/Barker-Stonehouse-Oct-22-2019-Set2-1011-scaled.jpg",
            "https://www.digsdigs.com/photos/2021/02/a-boho-working-space-with-a-color-block-yellow-wall-a-desk-with-a-cork-top-a-cofy-chair-an-open-shelving-unit-and-some-cacti.jpg"
        ],
    },
    {
        id: 3,
        title: "Blue Kitchen Fairytale",
        parapgraphs: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, placeat eveniet ipsa saepe repellendus porro officiis similique suscipit exercitationem quae.", "Fusce venenatis enim sit amet nisl hendrerit dictum. Proin eget suscipit dui. Etiam dignissim est tellus, a euismod nibh dignissim sed. Pellentesque vel ante feugiat, maximus diam a, commodo risus. Aenean mattis ipsum in velit pulvinar, vitae fermentum felis accumsan. Cras placerat ipsum vitae tincidunt mattis. Donec quis neque eget mi porta faucibus. Vivamus purus nisi, ultrices vitae maximus nec, maximus ut lectus. Nulla elementum consectetur mattis. Nunc a turpis in ipsum pulvinar mattis. Vivamus aliquam quam quis nisl euismod, at tempus justo ultrices. Pellentesque ligula dolor, tempor a dolor sed, porta fermentum mauris.", " Nulla porttitor, libero vel auctor convallis, tellus odio feugiat sem, sed suscipit mi arcu at magna. Praesent tincidunt lobortis dui, nec condimentum purus dapibus sit amet. Suspendisse efficitur rhoncus leo. Etiam sagittis neque sed tincidunt pulvinar. Suspendisse enim ligula, finibus et justo quis, viverra dapibus ante. Phasellus ut suscipit urna. Nullam nunc tellus, scelerisque quis mi sed, venenatis dignissim elit. Aliquam ultricies sem eget elit ullamcorper, non pharetra metus imperdiet. Sed vulputate justo eget velit pulvinar rutrum egestas et turpis. Donec dignissim hendrerit libero ut lobortis. Etiam efficitur ante posuere ipsum auctor, quis condimentum ligula sagittis. Integer feugiat elit vel lacinia euismod. ", "Donec congue erat risus, quis iaculis turpis tempus sed. Nulla eget luctus leo. Donec ex turpis, mollis non ligula in, luctus posuere enim. Sed nec lectus felis. Suspendisse cursus lorem vel tristique interdum. Aliquam dictum lacus lorem, id placerat magna tempor vel. Nam ultricies rutrum massa, eu rutrum nulla convallis sed. Donec eget bibendum nunc. Sed rutrum urna vel magna ultrices, cursus commodo mi aliquet. "],
        date: "25.01.2022",
        images: ["https://cdn.decoist.com/wp-content/uploads/2020/01/Classic-deep-blue-in-the-kitchen-bright-by-the-dashing-island-cabinets-and-bar-stools.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Kitchen-hood-color-matches-with-the-color-of-the-island-in-blue.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Shaker-style-cabinets-in-deep-blue-steal-the-show-inside-this-eclectic-gallery-kitchen.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Craftsman-style-kitchen-in-Classic-Blue-and-white-with-wooden-ceiling-beams.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Hint-of-deep-blue-for-the-kitchen-in-white.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Explore-and-combine-different-hues-of-deep-blue-in-the-kitchen-for-a-trendier-look.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Kitchen-in-white-with-blue-island-that-features-wine-storage-space-blue-pendants-and-skylights.jpg", "https://cdn.decoist.com/wp-content/uploads/2020/01/Pick-a-shade-of-deep-blue-along-with-white-in-the-sleek-single-wall-contemporary-kitchen.jpg"]
    }
]